export const DataJobs = [
  {
    employer_name: "Company Name",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRozpyZ2-Blq6K0b_7uk1IBsPMU6UbpYVLrjwqL&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Radley James",
    job_id: "ZLHPTnm0vUZhlFhdAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer – Houston, TX (Hybrid)",
    job_apply_link:
      "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.708,
    apply_options: [
      {
        publisher: "Radley James",
        apply_link:
          "https://www.radleyjames.com/job/python-developer-houston-tx-hybrid/",
        is_direct: false,
      },
      {
        publisher: "Learn4Good",
        apply_link:
          "https://www.learn4good.com/jobs/houston/texas/info_technology/2724195958/e/",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/8eb6NOWrLE7-5vUGo9Jz0H9GxiB6dmhCVa7gASCkSIFwD1tVMbqLmA",
        is_direct: false,
      },
      {
        publisher: "Jooble",
        apply_link:
          "https://jooble.org/jdp/-728135481221022673/Python-Developer-+-Houston%2C-TX-(Hybrid)-Houston%2C-TX",
        is_direct: false,
      },
    ],
    job_description:
      "Python Developer\n\nHouston, Texas, United States (Hybrid)\n\nA leading hedge fund with a global reputation for being one of the best in the industry is looking to add a mid to senior developer to its Houston office.\n\nThis individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants.\n\nQualifications:\n• Computer science or related degree from a top university\n• 3+ years experience in Python, Beautiful Soup, Selenium, etc.\n• Experience with AWS, docker, Kubernetes are all a plus\n\nIndustry-leading compensation on offer with exceptional bonuses\n\nIf interested please get in touch by applying or at Volkan.ozbicer@radleyjames.com with your resume if you have further questions.",
    job_is_remote: false,
    job_posted_at_timestamp: 1694595106,
    job_posted_at_datetime_utc: "2023-09-13T08:51:46.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=ZLHPTnm0vUZhlFhdAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Computer science or related degree from a top university",
        "3+ years experience in Python, Beautiful Soup, Selenium, etc",
      ],
      Responsibilities: [
        "This individual will be working on expanding their global analytics and trading-related tools and APIs, liaising between external and internal sources and tools of data and databases to create new pipelines as well as helping create analytics apps to be used by the traders, data scientists and quants",
      ],
      Benefits: [
        "Industry-leading compensation on offer with exceptional bonuses",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Magnus Technology Solutions",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6jDxj9ijK5FI1q7aYX2LJr7YxTpzqyPhX_-tp&s=0",
    employer_website: "http://www.magnustechnol.com",
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_id: "70TAzH8W_MHzd5k5AAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer (Entry Level)",
    job_apply_link:
      "https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-(Entry-Level)/-in-Dallas,TX?jid=fd404ba337347616",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7056,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/Magnus-Technology-Solutions/Job/Python-Developer-(Entry-Level)/-in-Dallas,TX?jid=fd404ba337347616",
        is_direct: true,
      },
    ],
    job_description:
      "We are seeking a Python Developer (Entry Level) to become an integral part of our team! You will be responsible for creating and modifying computer application software or specialized utility programs.\n\nResponsibilities:\n• Analyze user needs and develop software solutions\n• Work with project manager or product owner to meet specification needs\n• Recommend software upgrades to optimize operational efficiency\n• Collaborate with other developers to design and optimize code\n• Create flowcharts and user guides for new and existing programs\n• Document all programming tasks and procedures\n• Perform routine software maintenance\n\nQualifications:\n• Previous experience in software development, computer engineering, or other related fields\n• Knowledge of Java, Python, or other programming languages\n• Familiarity with relational databases such as MySQL, Oracle, and SQL Server\n• Deadline and detail-oriented\n• Strong analytical and critical thinking skills\n\nCompany DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA. We work on #Selenium, #QA_Testing, #QA_Automation, #Manual_Testing #Dotnet, #java, #j2ee, #java_UI, #Angular, #React, #Python, #DevOps, #Salesforce, #Hadoop, #IOS, #Android, #RPA, #Mulesoft and any #Developer related #Technologies.",
    job_is_remote: true,
    job_posted_at_timestamp: 1702908423,
    job_posted_at_datetime_utc: "2023-12-18T14:07:03.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=70TAzH8W_MHzd5k5AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-01-21T00:00:00.000Z",
    job_offer_expiration_timestamp: 1705795200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 80000,
    job_max_salary: 100000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Previous experience in software development, computer engineering, or other related fields",
        "Knowledge of Java, Python, or other programming languages",
        "Familiarity with relational databases such as MySQL, Oracle, and SQL Server",
        "Deadline and detail-oriented",
        "Strong analytical and critical thinking skills",
        "Company DescriptionMagnus Technology Solutions provide quick orientation / training for professionals & placement for candidates having work authorization in USA",
      ],
      Responsibilities: [
        "You will be responsible for creating and modifying computer application software or specialized utility programs",
        "Analyze user needs and develop software solutions",
        "Work with project manager or product owner to meet specification needs",
        "Recommend software upgrades to optimize operational efficiency",
        "Collaborate with other developers to design and optimize code",
        "Create flowcharts and user guides for new and existing programs",
        "Document all programming tasks and procedures",
        "Perform routine software maintenance",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "15-1132.00: Software Developers, Applications",
    ],
  },
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "diarenuUzQgtpLz1AAAAAA==",
    job_employment_type: "PARTTIME",
    job_title: "Python Developer (Entry Level)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-synergisticit-3767597019",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6992,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-entry-level-at-synergisticit-3767597019",
        is_direct: false,
      },
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/SynergisticIT/Job/Python-Developer-(Entry-Level)/-in-Dallas,TX?jid=c42bdc40190a6c76",
        is_direct: false,
      },
      {
        publisher: "Talent.com",
        apply_link: "https://www.talent.com/view?id=933e6b61141b",
        is_direct: false,
      },
    ],
    job_description:
      "SynergisticIT is committed to fast track your career by increasing your career prospects. We provide a broad spectrum of career advancement solutions. Whether you are struggling to find a job or hustling to get noticed by the hiring managers, we can help you stand out in your professional endeavors.\n\nTrusted by thousands of tech enthusiasts, SynergisticIT can bridge your skill and knowledge gap to make you competent for high-tech jobs. Our invaluable business acumen helps us assist thriving job seekers in achieving their career goals.\n\nCurrently, we are looking for adept entry-level Python Developers to work with our elite group of clients, namely Client, PayPal, Expedia Group, Google, Apple, Cognizant, Ford, Cisco, Walmart Labs, etc.\n\nRequired Qualifications And Background\n• Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,\n• Mathematics or Statistics background\n\nSkills Required\n• 0 to 2 years of experience in Python development\n• Deep understanding of the software development life cycle\n• Knowledge of Linear Algebra, Statistics, and Mathematics concepts\n• Excellent written and verbal communication skills\n• Technically inquisitive, self-learner, team player, and highly motivated\n• Strong work ethics and creative problem-solving abilities\n\nPreferred Skills\n• Deep Learning\n• Data visualization\n• Scala\n• NLP\n• Django\n\nRoles and Responsibilities\n\nAs an entry-level Python Developer, you need to perform the following duties:\n• Write server-side web application logic\n• Write scalable and effective codes in Python\n• Develop backend components to boost overall application's performance\n• Executing tests and fixing bugs in applications and software\n• Implement data protection and security solutions\n• Connect applications with third-party web services\n• Support frontend developers by integrating UI elements into Python applications\n\nBenefits\n• Competitive salary\n• Flexible work schedule & part-time off\n• E-verified\n• H1B Filing\n• No relocation\n• On job technical support\n• Skill Enhancement\n• Opportunity to work with Fortune 500 Companies\n\nWho can apply?\n\nThis job opportunity is best suited for recent IT graduates who want to make a mark in the tech industry and upskill their IT talent. Anyone with a basic knowledge of Python programming or having some experience in building Python software solutions can apply for this position.\n\nCandidate's Outcome : Best Programmers in USA | Best Coding Bootcamp - SynergisticIT\n\nNo third-party candidates or c2c candidates\n\nIf you are interested, please apply to the posting.\n\nNo phone calls please, Shortlisted candidates would be reached out.",
    job_is_remote: false,
    job_posted_at_timestamp: 1701177665,
    job_posted_at_datetime_utc: "2023-11-28T13:21:05.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=diarenuUzQgtpLz1AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-12-28T13:21:43.000Z",
    job_offer_expiration_timestamp: 1703769703,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree or Master's degree in Computer Science, Electrical Engineering, Computer Engineering, Information Systems, IT, Mathematics,",
        "Mathematics or Statistics background",
        "0 to 2 years of experience in Python development",
        "Deep understanding of the software development life cycle",
        "Knowledge of Linear Algebra, Statistics, and Mathematics concepts",
        "Excellent written and verbal communication skills",
        "Technically inquisitive, self-learner, team player, and highly motivated",
        "Strong work ethics and creative problem-solving abilities",
        "Support frontend developers by integrating UI elements into Python applications",
      ],
      Responsibilities: [
        "As an entry-level Python Developer, you need to perform the following duties:",
        "Write server-side web application logic",
        "Write scalable and effective codes in Python",
        "Develop backend components to boost overall application's performance",
        "Executing tests and fixing bugs in applications and software",
        "Implement data protection and security solutions",
        "Connect applications with third-party web services",
      ],
      Benefits: [
        "Competitive salary",
        "Flexible work schedule & part-time off",
        "No relocation",
        "On job technical support",
        "Opportunity to work with Fortune 500 Companies",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "EvE0hgo_kW-jfRIXAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Entry level python developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3767592655",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6992,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/entry-level-python-developer-at-synergisticit-3767592655",
        is_direct: false,
      },
      {
        publisher: "Talent.com",
        apply_link: "https://www.talent.com/view?id=6974d0ae799c",
        is_direct: false,
      },
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Software-Developer/-in-Dallas,TX?jid=2308a1b1e7f0f60a",
        is_direct: false,
      },
      {
        publisher: "CareerBuilder",
        apply_link: "https://www.careerbuilder.com/job/J3Q73T6T29WNX3N7VM3",
        is_direct: false,
      },
      {
        publisher: "Learn4Good",
        apply_link:
          "https://www.learn4good.com/jobs/dallas/texas/info_technology/2765780557/e/",
        is_direct: false,
      },
      {
        publisher: "Jooble",
        apply_link:
          "https://jooble.org/jdp/678995149291283252/Entry-Level-Python-Developer-Dallas%2C-TX",
        is_direct: false,
      },
      {
        publisher: "Lensa",
        apply_link:
          "https://lensa.com/entry-level-python-developer-jobs/dallas/jd/434ec2c4bd692a64174f40f5a8ccb34c",
        is_direct: false,
      },
      {
        publisher: "Restaurants Of Beaverton Oregon",
        apply_link:
          "https://restaurantsofbeaverton.com/joblib/job/entry-level-python-developer-at-synergisticit-dallas-tx-Wm5tcEw0aDcwQUtkZEc1RUNrcU9OQk9KRVE9PQ==",
        is_direct: false,
      },
    ],
    job_description:
      "SYNERGISTICIT is aware that the Job Market is Challenging because of Tech Layoffs. The Job market is flooded with hundreds and thousands of laid-off Jobseekers competing with existing Jobseekers. For entry-level Job seekers to get client interviews and jobs they need to differentiate themselves by ensuring they have exceptional skills and technologies to be noticed by clients.\n\nSince 2010 we have helped Jobseekers differentiate themselves by providing clients with candidates who have the requisite skills and experience to outperform at interviews and clients. Here at SynergisticIT We just don't focus on getting you a Job we make careers. All Positions are open for all visas and US citizens We at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like Apple, Google, and Paypal, western union, Client, visa, Walmart labs, etc., to name a few. We have an excellent reputation with the clients. Currently, we are looking for Entry level python developer\n\nWho Should Apply Recent Computer Science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry We welcome candidates with all visas and citizens to apply. We assist in filing for STEM extension and also for H1b and Green card filing to Candidates\n\nWe also offer Skill enhancement programs for candidates who are either missing skills or lacking Industry/Client experience with Projects and skills. Candidates have difficulty finding jobs or cracking interviews or want to improve their skill portfolio. If they are qualified with enough skills and have hands-on project work with clients then no need for skill enhancement.\n\nCandidates can benefit from skill enhancement if they fall into the below categories.\n\nCandidates who Lack Experience or are fresher with No actual Job experience with projects with clients who Have had a break in careers Lack Technical Competency or skills being demanded by clients Different visa candidates (Like OPT/H4EAD/L2EAD) who want to get employed and settle down in the USA please check the below links to see success outcomes of our candidates https://www.synergisticit.com/candidate-outcomes/\n\nWatch the below videos of us participating in Industry events with the Top companies in Technology at Oracle Cloud World/Oracle Java One (Las Vegas) and at Gartner Data Analytics Summit (Florida)\n\nOracle Cloud World Event (OCW) Las Vegas 2022 | SynergisticIT - YouTube https://www.youtube.com/watch?v=OAFOhcGy9Z8\n\nhttps://www.youtube.com/watch?v=EmO7NrWHkLM https://www.youtube.com/watch?v=NVBU9RYZ6UI\n\nhttps://www.youtube.com/watch?v=Yy74yvjatVg SynergisticIT at Gartner Data and Analytics Summit 2023 - YouTube\n\nhttps://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/contact-us/\n\nIf you have relevant skills and industry experience, please apply if not then candidates can opt for Skill enhancement.\n\nFor getting help with interviews please visit\n\nhttps://www.synergisticit.com/interview-questions/\n\nREQUIRED SKILLS For Java /Software Programmers\n• Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Project work on the skills\n• Knowledge of Core Java, java script, C++ or software programming\n• Spring boot, Micro-services, Docker, Jenkins and REST API's experience\n• Excellent written and verbal communication skills\n\nFor data Science/Machine learning\n\nRequired Skills\n• Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Project work on the technologies needed\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in the programming language Java and understanding of the software development life cycle\n• Knowledge of Statistics, SAS, Python, Computer Vision, and data visualization tools\n• Excellent written and verbal communication skills\n\nPreferred skills: NLP, Text mining, Tableau, Power BI, Time series analysis\n\nPlease understand skills and relevant experience on real-world projects are required by clients for selection even if it's a Junior or entry-level position the additional skills and Project work with hands-on experience building projects at the client site are the only way a candidate can be picked by clients. If not having the skills or hands-on project work at the client site, candidates can opt for skill enhancement to gain the required skills and project work. No third-party candidates or c2c candidates\n\nplease only apply to the posting\n\nNo phone calls, please. Shortlisted candidates would be reached out to.",
    job_is_remote: false,
    job_posted_at_timestamp: 1701177673,
    job_posted_at_datetime_utc: "2023-11-28T13:21:13.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=EvE0hgo_kW-jfRIXAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-12-28T13:21:56.000Z",
    job_offer_expiration_timestamp: 1703769716,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "REQUIRED SKILLS For Java /Software Programmers",
        "Bachelor's degree or Master's degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT",
        "Highly motivated, self-learner, and technically inquisitive",
        "Experience in programming language Java and understanding of the software development life cycle",
        "Knowledge of Core Java, java script, C++ or software programming",
        "Spring boot, Micro-services, Docker, Jenkins and REST API's experience",
        "Excellent written and verbal communication skills",
        "For data Science/Machine learning",
        "Project work on the technologies needed",
        "Knowledge of Statistics, SAS, Python, Computer Vision, and data visualization tools",
        "Please understand skills and relevant experience on real-world projects are required by clients for selection even if it's a Junior or entry-level position the additional skills and Project work with hands-on experience building projects at the client site are the only way a candidate can be picked by clients",
        "If not having the skills or hands-on project work at the client site, candidates can opt for skill enhancement to gain the required skills and project work",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_id: "_2zrRnwarpf3YwwEAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Entry Level Python Developer",
    job_apply_link:
      "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer/-in-Houston,TX?jid=b5db608a2de13d7e",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5867,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer/-in-Houston,TX?jid=b5db608a2de13d7e",
        is_direct: false,
      },
      {
        publisher: "JobLookup",
        apply_link:
          "https://joblookup.com/us/job/entry-level-python-developer-job-in-houston-tx",
        is_direct: false,
      },
      {
        publisher: "Jobilize",
        apply_link:
          "https://www.jobilize.com/job/us-tx-houston-entry-level-python-developer-synergisticit-hiring-now",
        is_direct: false,
      },
    ],
    job_description:
      "About Us:\nSynergistic IT is a full-service staffing and placement firm servicing client in America for the past 12+ years. We are dedicated towards fulfilling the IT needs of our clients. From staffing to full implementation of projects we provide the highest quality IT Services. We Intend to deliver exceptional student outcome. We don't just help you secure a tech job but build a solid career in technology.\n\nJob Description:\n• Should know how to work in large verities of libraries, frameworks, and modules\n• Duck typing, string, tuple and Lambda knowledge required\n• Django Frame work required\n• Worked on Django model, CBV, Django CRUD operation\n\nSkills Required-\n• Knowledge of Python web frameworks and event-driven programming in Python.\n• Basic understanding of front-end technologies.\n• High attention to detail.\n• Excellent communication and problem-solving skills.\n• Proficient understanding of code versioning tools\n• Know the classes of SCALA, Traits of SCALA, and Collection of SCALA\n\nEducation Requirement: -\nBachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering.\n\nBenefits:\n• On Job Technical support\n• E- verified\n• Help to get H1B Employer.\n• Full time position\n\nCandidate who are missing the required skills, might be provided an option to enhance their skills, so that they can also apply for the role and can make a career in IT industry.\n\nIf you do respond via e-mail, please include a daytime phone number so that we can reach you. In considering candidates, time is of the essence, so please respond ASAP. Thank you",
    job_is_remote: false,
    job_posted_at_timestamp: 1670227200,
    job_posted_at_datetime_utc: "2022-12-05T08:00:00.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=_2zrRnwarpf3YwwEAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-01-21T00:00:00.000Z",
    job_offer_expiration_timestamp: 1705795200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Knowledge of Python web frameworks and event-driven programming in Python",
        "Basic understanding of front-end technologies",
        "High attention to detail",
        "Excellent communication and problem-solving skills",
        "Proficient understanding of code versioning tools",
        "Know the classes of SCALA, Traits of SCALA, and Collection of SCALA",
        "Bachelors, Masters in Computer Science/ Computer Engineering/ Information Systems/Information Technology/ Electrical Engineering/ Mechanical Engineering",
      ],
      Responsibilities: [
        "Should know how to work in large verities of libraries, frameworks, and modules",
        "Django Frame work required",
        "Worked on Django model, CBV, Django CRUD operation",
      ],
      Benefits: ["On Job Technical support", "Full time position"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "15-1132.00: Software Developers, Applications",
    ],
  },
  {
    employer_name: "Dice",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKlgydP7sElaJC9qPrtNHwBhyTMHYgii1RPWsy&s=0",
    employer_website: null,
    employer_company_type: "Information",
    job_publisher: "Jobgether",
    job_id: "kAJhRp1STtLSsuR7AAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer - Remote from Texas (USA)",
    job_apply_link:
      "https://jobgether.com/offer/6539190b64a13bb96e8b2987-python-developer-remote",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5638,
    apply_options: [
      {
        publisher: "Jobgether",
        apply_link:
          "https://jobgether.com/offer/6539190b64a13bb96e8b2987-python-developer-remote",
        is_direct: false,
      },
    ],
    job_description:
      'This a Full Remote job, the offer is available from: Texas (USA)\n\n"\n\nDice is the leading career destination for tech experts at every stage of their careers. Our client, Dunhill Professional Search, is seeking the following. Apply via Dice today! **\n\nPosition Description:**\n• Attend Daily Scrum calls communicating your accomplishments, objectives, and blockers\n• Decompose User Stories and Tasks into subtasks required to complete, along with acceptance criteria\n• Implement User Stories using feature branches\n• Commit code changes regularly and merge feature branches when they are complete\n• Participate in code review processes\n• Utilize Sonarqube to track code coverage to maintain target levels of unit test coverage\n• Attend Daily Scrum calls communicating your accomplishments, objectives, and blockers\n• Attend and present at Sprint Demos to incorporate customer feedback into future work\n• Participate in Sprint retrospective and offer ideas for process improvement\n• Contribute to system documentation like version description documents, system administration manual, data mapping, and system installation guide.\n• Provide support to DHA and Cloud One teams for deployment during development\n\nRequirements :\n• with a Bachelor\'s degree in computer science, engineering, or related field preferred\n• Strong Python experience\n• Strong Object-Oriented programmer\n• Familiarity with micro-service architecture\n• Develop, maintain, and enhance web applications using Python, Django, and FastAPI.\n• Design, create, and optimize database schemas in PostgreSQL.\n• Implement and maintain unit tests for code quality and reliability.\n• Collaborate with the development team to architect and build scalable solutions.\n• Utilize software design patterns to create efficient and maintainable code.\n• Contribute to code reviews and provide constructive feedback to team members.\n• Troubleshoot and resolve software defects and issues.\n• Stay up-to-date with industry best practices and emerging technologies.\n• Strong communication skills and the ability to work collaboratively in a team.\n• Self-motivated, detail-oriented, and able to manage multiple tasks and changing priorities.\n\nNice to haves :\n• Experience working with healthcare data in interoperable formats (e.g. HL7, FHIR, strong emphasis on HL7)\n• Intermediate Java Experience\n• Experience with secure coding principles, software security remediations, and STIGs\n• Some AWS Cloud native experience\n• Strong understanding of Agile principles\n• Experience with Docker/Kubernetes/Gitlab CI/CD a plus\n\n#cjpost\n\nPython Developer - Remote\n\n"This offer from "Dice" has been enriched by Jobgether and got a 78.5% flex score.',
    job_is_remote: true,
    job_posted_at_timestamp: 1698237857,
    job_posted_at_datetime_utc: "2023-10-25T12:44:17.000Z",
    job_city: "San Antonio",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.42519,
    job_longitude: -98.49459,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=kAJhRp1STtLSsuR7AAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-03-20T23:00:00.000Z",
    job_offer_expiration_timestamp: 1710975600,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong Python experience",
        "Strong Object-Oriented programmer",
        "Familiarity with micro-service architecture",
        "Develop, maintain, and enhance web applications using Python, Django, and FastAPI",
        "Stay up-to-date with industry best practices and emerging technologies",
        "Strong communication skills and the ability to work collaboratively in a team",
        "Self-motivated, detail-oriented, and able to manage multiple tasks and changing priorities",
        "Experience working with healthcare data in interoperable formats (e.g. HL7, FHIR, strong emphasis on HL7)",
        "Intermediate Java Experience",
        "Experience with secure coding principles, software security remediations, and STIGs",
        "Some AWS Cloud native experience",
        "Strong understanding of Agile principles",
      ],
      Responsibilities: [
        "Attend Daily Scrum calls communicating your accomplishments, objectives, and blockers",
        "Decompose User Stories and Tasks into subtasks required to complete, along with acceptance criteria",
        "Implement User Stories using feature branches",
        "Commit code changes regularly and merge feature branches when they are complete",
        "Participate in code review processes",
        "Utilize Sonarqube to track code coverage to maintain target levels of unit test coverage",
        "Attend and present at Sprint Demos to incorporate customer feedback into future work",
        "Participate in Sprint retrospective and offer ideas for process improvement",
        "Contribute to system documentation like version description documents, system administration manual, data mapping, and system installation guide",
        "Provide support to DHA and Cloud One teams for deployment during development",
        "Design, create, and optimize database schemas in PostgreSQL",
        "Implement and maintain unit tests for code quality and reliability",
        "Collaborate with the development team to architect and build scalable solutions",
        "Utilize software design patterns to create efficient and maintainable code",
        "Contribute to code reviews and provide constructive feedback to team members",
        "Troubleshoot and resolve software defects and issues",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_naics_code: "519130",
    job_naics_name:
      "Internet Publishing and Broadcasting and Web Search Portals",
  },
  {
    employer_name: "Saransh Inc",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDq_scllIjMNu5-EEfbOybq-69TTSjWDp5JJIb&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "3SbtHDni2DKLVenFAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-saransh-inc-3753018207",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6874,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-saransh-inc-3753018207",
        is_direct: false,
      },
      {
        publisher: "SimplyHired",
        apply_link:
          "https://www.simplyhired.com/job/vIcNpPpTZD5l7Cq1SGlLew78bQA5cs9YY4n_1I9qB6h-DXHtGc1vhQ",
        is_direct: false,
      },
      {
        publisher: "BeBee",
        apply_link:
          "https://us.bebee.com/job/20231217-fa896c9e35dac638e1a0534aef8a1d06",
        is_direct: false,
      },
      {
        publisher: "Lensa",
        apply_link:
          "https://lensa.com/python-developer-jobs/plano/jd/85554f9400fc6c319f8e7811339fbfaa",
        is_direct: false,
      },
    ],
    job_description:
      "• Need someone who can build base framework object oriented with an objective to build SDKs to expose KPIs as API to various consumptions.\n• Strong programming experience with Python\n• Should have exposure on CI/CD\n• Hands-on Experience on SQL\n• Nice to have OpenShift experience.\n• Experience using databases and object-oriented design in python mandatory.",
    job_is_remote: false,
    job_posted_at_timestamp: 1698942928,
    job_posted_at_datetime_utc: "2023-11-02T16:35:28.000Z",
    job_city: "Plano",
    job_state: "TX",
    job_country: "US",
    job_latitude: 33.019844,
    job_longitude: -96.69888,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=3SbtHDni2DKLVenFAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-04-30T16:35:30.000Z",
    job_offer_expiration_timestamp: 1714494930,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong programming experience with Python",
        "Should have exposure on CI/CD",
        "Hands-on Experience on SQL",
        "Nice to have OpenShift experience",
        "Experience using databases and object-oriented design in python mandatory",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "ZipRecruiter",
    job_id: "Igbv8bfzTXdNVxDAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Entry Level Python Developer (Remote)",
    job_apply_link:
      "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer-(Remote)/-in-Houston,TX?jid=5b8da794ca11313b",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6842,
    apply_options: [
      {
        publisher: "ZipRecruiter",
        apply_link:
          "https://www.ziprecruiter.com/c/SynergisticIT/Job/Entry-Level-Python-Developer-(Remote)/-in-Houston,TX?jid=5b8da794ca11313b",
        is_direct: false,
      },
      {
        publisher: "Jooble",
        apply_link:
          "https://jooble.org/jdp/-3481101953432488051/Entry-Level-Python-Developer-(Remote)-Houston%2C-TX",
        is_direct: false,
      },
    ],
    job_description:
      "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need\n\nWe at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like apple, google, Paypal, western union, Client, visa, walmart labs etc to name a few.\n\nWe have an excellent reputation with the clients. Currently, We are looking for entry-level software programmers, IT enthusiasts, Python/Java developers, Data analysts/ Data Scientists.\n\nWho Should Apply Recent IT Graduates looking to make their careers in IT Industry Candidates having basic knowledge or with one or two years of experience in JAVA, C++, Core JAVA.\n\nWe welcome candidates with all visas and citizens to apply.\n\nWe assist in filing for STEM extension and also for H1b and Green card filing to Candidates looking to upskill/enhance their IT skills.\n\nCandidates who are serious about their future in the IT Industry and have set big goals for themselves.\n\nCandidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill enhancement programs if the candidates are missing skills or experience which our clients need with great outcomes\n\nCandidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement\n\nCandidates who Lack Experience\nHave had a break in careers\nLack Technical Competency\nDifferent visa candidates who want to get employed and settle down in the USA\n\nplease also check the below links\n\nhttps://www.synergisticit.com/candidate-outcomes/\n\nhttps://www.synergisticit.com/java-track/\n\nhttps://www.synergisticit.com/data-science-track/\n\nhttps://www.synergisticit.com/blog/\nREQUIRED SKILLS\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Knowledge of Core Java , javascript , C++ or software programming\n• Excellent written and verbal communication skills\nPreferred skills: knowledge of Spring Boot, microservices\n\nPlease understand skills are required by clients for selection even if its Junior or entry level position the additional skills are the only way a candidate can be picked by clients.\nNo third party candidates or c2c candidates\nTo apply for this position, please apply to the posting\n\nNo phone calls please . Shortlisted candidates would be reached out\n\nSYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need\n\nPosition open for all visas and US citizens\n\nWe at Synergisticit understand the problem of the mismatch between employer's requirements and Employee skills and that's why since 2010 we have helped thousands of candidates get jobs at technology clients like apple, google, Paypal, western union, Client, visa, walmart labs etc to name a few.\n\nWe have an excellent reputation with the clients. Currently, We are looking for entry-level software programmers, IT enthusiasts, Python/Java developers, Data analysts/ Data Scientists.\n\nWho Should Apply Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry\n\nWe welcome candidates with all visas and citizens to apply.\n\nWe assist in filing for STEM extension and also for H1b and Green card filing to Candidates\n\nCandidates who are serious about their future in the IT Industry and have set big goals for themselves.\n\nCandidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill enhancement programs if the candidates are missing skills or experience which our clients need with great outcomes\n\nCandidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement\n\nCandidates who Lack Experience\nHave had a break in careers\nLack Technical Competency\nDifferent visa candidates who want to get employed and settle down in the USA\n\nplease also check the below links\n\nhttps://www.synergisticit.com/candidate-outcomes/\n\nhttps://www.synergisticit.com/java-track/\n\nhttps://www.synergisticit.com/data-science-track/\n\nhttps://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/\n\nhttps://www.synergisticit.com/contact-us/\n\nIf not a match candidates can opt for Skill enhancement\nREQUIRED SKILLS For java / Software Programmers\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Knowledge of Core Java , javascript , C++ or software programming\n• Spring boot, Microservices and REST API's experience\n• Excellent written and verbal communication skills\nFor data Science/Machine learning\nREQUIRED SKILLS\n• Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT\n• Highly motivated, self-learner, and technically inquisitive\n• Experience in programming language Java and understanding of the software development life cycle\n• Knowledge of Statistics, Python, data visualization tools\n• Excellent written and verbal communication skills\nPreferred skills: NLP, Text mining, Tableau, Time series analysis\nPlease understand skills are required by clients for selection even if its Junior or entry level position the additional skills are the only way a candidate can be picked by clients.\n\nNo third party candidates or c2c candidates\n\nPlease understand skills are required by clients for selection even if its Junior or entry level position the additional skills are the only way a candidate can be picked by clients.\n\nNo third party candidates or c2c candidates\nplease apply to the posting\n\nNo phone calls please. Shortlisted candidates would be reached out",
    job_is_remote: false,
    job_posted_at_timestamp: 1674720000,
    job_posted_at_datetime_utc: "2023-01-26T08:00:00.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=Igbv8bfzTXdNVxDAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-01-21T00:00:00.000Z",
    job_offer_expiration_timestamp: 1705795200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 12,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Who Should Apply Recent IT Graduates looking to make their careers in IT Industry Candidates having basic knowledge or with one or two years of experience in JAVA, C++, Core JAVA",
        "Different visa candidates who want to get employed and settle down in the USA",
        "Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT",
        "Highly motivated, self-learner, and technically inquisitive",
        "Experience in programming language Java and understanding of the software development life cycle",
        "Knowledge of Core Java , javascript , C++ or software programming",
        "Excellent written and verbal communication skills",
        "Please understand skills are required by clients for selection even if its Junior or entry level position the additional skills are the only way a candidate can be picked by clients",
        "Who Should Apply Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates looking to make their careers in IT Industry",
        "Spring boot, Microservices and REST API's experience",
        "For data Science/Machine learning",
        "Knowledge of Statistics, Python, data visualization tools",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "15-1132.00: Software Developers, Applications",
    ],
  },
  {
    employer_name: "G-Research",
    employer_logo:
      "https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/gtqacyz2dx8jqicpnmqr",
    employer_website: "http://www.gresearch.co.uk",
    employer_company_type: null,
    job_publisher: "Learn4Good",
    job_id: "6Q3aX9S2WRf7HEBoAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Software Engineer, Backend Developer, Python",
    job_apply_link:
      "https://www.learn4good.com/jobs/online_remote/software_development/2784126283/e/",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.4676,
    apply_options: [
      {
        publisher: "Learn4Good",
        apply_link:
          "https://www.learn4good.com/jobs/online_remote/software_development/2784126283/e/",
        is_direct: false,
      },
    ],
    job_description:
      "Location :\nDallas, TX\n\nThis is a hybrid role, based in G-Research's office in Dallas.\n\nG-Research is Europe's leading quantitative finance research firm. We hire the brightest minds in the world to tackle some of the biggest questions in finance. We pair this expertise with machine learning, big data, and some of the most advanced technology available to predict movements in financial markets.\n\nThis role is based in G-Research's office in Dallas. Opened in 2022, the Dallas office is a key infrastructure hub where we work on the latest technologies in a cutting-edge environment.\n\nThe Role\n\nThe Trading Ecosystem Engineering (TEE) team builds and operates the key systems, workflows and services that our internal users and customer teams rely on in their research.\n\nCurrently, we build our own systems in-house, but we are also looking to adopt more Open Source Software in the future.\n\nOur Engineers are full-stack, with a stronger predominance for back-end, and we work closely with internal and external customers to understand their needs and drive best practice through our deep knowledge engineering best practices.\n\nKey responsibilities of the role include:\n\nCrafting large-scale, highly available and reliable service-oriented systems\n\nOptimising and troubleshooting software performance\n\nDesigning APIs for use in a real-time environment\n\nFront-end web development\n\nBuilding strong, collaborative relationships with technical and non-technical stakeholders, focussing on maximising business value from TEE's work\n\nSteering, and contributing to the technical deliverables of your team, ensuring that the requirements of the business are met by making data driven decisions\n\nParticipating and actively engaging with the incident management process and a blameless continuous learning culture\n\nEnsuring the smooth running of a geographically distributed team\n\nWho are we looking for?\n\nWe are looking for a Software Engineer who is motivated and passionate about solving challenging software issues that make a difference to G-Research.\n\nThe ideal candidate will have the following skills and experience:\n\nDevelopment capabilities with one or more high level languages, preferably C#, Angular and Type Script\n\nObject-oriented programming and strong problem solving skills\n\nA proactive approach to spotting problems, areas for improvement, performance bottlenecks, and process improvements\n\nThe ability to understand the inherent trade-offs between various software architectures as it relates to performance, resiliency and fault tolerance, load balancing, and data consistency\n\nDon't feel you need to tick all of these boxes. If you are a smart, motivated, passionate Software Engineer then we want to hear from you.\n\nWhy should you apply?\n\nMarket-leading compensation plus annual discretionary bonus\n\nInformal dress code and excellent work/life balance\n\nExcellent paid time off allowance\n\nSick days, military leave, and family and medical leave\n\nGenerous 401(k) plan\n\n16-weeks' fully paid parental leave\n\nMedical and Prescription, Dental, and Vision insurance\n\nLife and Accidental Death & Dismemberment (AD&D) insurance\n\nEmployee Assistance and Wellness programs\n\nGenerous relocation allowance and support\n\nGreat selection of office snacks, and hot and cold drinks\n\nOn-site gym and car park\n\nG-Research is committed to cultivating and preserving an inclusive work environment. We are an ideas-driven business and we place great value on diversity of experience and opinions.\n\nWe want to ensure that applicants receive a recruitment experience that enables them to perform at their best. If you have a disability or special need that requires accommodation please let us know in the relevant section.",
    job_is_remote: true,
    job_posted_at_timestamp: 1703203200,
    job_posted_at_datetime_utc: "2023-12-22T00:00:00.000Z",
    job_city: "Dallas",
    job_state: "TX",
    job_country: "US",
    job_latitude: 32.776665,
    job_longitude: -96.79699,
    job_benefits: [
      "paid_time_off",
      "health_insurance",
      "retirement_savings",
      "dental_coverage",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=6Q3aX9S2WRf7HEBoAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-06-21T00:00:00.000Z",
    job_offer_expiration_timestamp: 1718928000,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Front-end web development",
        "Development capabilities with one or more high level languages, preferably C#, Angular and Type Script",
        "Object-oriented programming and strong problem solving skills",
        "A proactive approach to spotting problems, areas for improvement, performance bottlenecks, and process improvements",
        "The ability to understand the inherent trade-offs between various software architectures as it relates to performance, resiliency and fault tolerance, load balancing, and data consistency",
      ],
      Responsibilities: [
        "The Trading Ecosystem Engineering (TEE) team builds and operates the key systems, workflows and services that our internal users and customer teams rely on in their research",
        "Crafting large-scale, highly available and reliable service-oriented systems",
        "Optimising and troubleshooting software performance",
        "Designing APIs for use in a real-time environment",
        "Steering, and contributing to the technical deliverables of your team, ensuring that the requirements of the business are met by making data driven decisions",
        "Participating and actively engaging with the incident management process and a blameless continuous learning culture",
        "Ensuring the smooth running of a geographically distributed team",
      ],
      Benefits: [
        "Market-leading compensation plus annual discretionary bonus",
        "Informal dress code and excellent work/life balance",
        "Excellent paid time off allowance",
        "Sick days, military leave, and family and medical leave",
        "Generous 401(k) plan",
        "16-weeks' fully paid parental leave",
        "Medical and Prescription, Dental, and Vision insurance",
        "Life and Accidental Death & Dismemberment (AD&D) insurance",
        "Employee Assistance and Wellness programs",
        "Generous relocation allowance and support",
      ],
    },
    job_job_title: "Software engineer",
    job_posting_language: "en",
    job_onet_soc: "15113300",
    job_onet_job_zone: "4",
    job_occupational_categories: [
      "Python",
      "Backend Developer",
      "Software Engineer",
    ],
  },
  {
    employer_name: "TEKFORTUNE INC",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-1EOWwXswTfNafOUGn0ohxTwRODjuuIAaaZ6s&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "qAguPGTIMiLKIsesAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Python Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/python-developer-at-tekfortune-inc-3768047814",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.676,
    apply_options: [
      {
        publisher: "LinkedIn",
        apply_link:
          "https://www.linkedin.com/jobs/view/python-developer-at-tekfortune-inc-3768047814",
        is_direct: false,
      },
      {
        publisher: "Talent.com",
        apply_link: "https://www.talent.com/view?id=4d23ee3c9478",
        is_direct: false,
      },
      {
        publisher: "Jobilize",
        apply_link:
          "https://www.jobilize.com/job/us-tx-austin-python-developer-tekfortune-hiring-now-job-immediately",
        is_direct: false,
      },
    ],
    job_description:
      "Tekfortune is a fast-growing consulting firm specialized in permanent, contract & project-based staffing services for worlds leading organizations in a broad range of industries. In this quickly changing economic landscape, virtual recruiting and remote work are critical for the future of work. To support the active project demands and skills gaps, our staffing experts can help you find the best job for you.\n\nTitle Python Developer\n\nLocation Remote\n\nContract\n\nRequired\n\n12+ years of experience in python development\n\n10+ years of experience in UNIT test\n\n10+ years of experience in Python FLASK development\n\n8+ years of experience in building API/microservices development\n\n6+ years of experience in GitHub\n\nHands on experiences in AWS lambda, CloudFront, S3 & EKS\n\nHands on experience in Docker\n\nNice to have Octopus & TeamCity experience.\n\nFor more information and other jobs available please contact our recruitment team at careers@tekfortune.com . To view all the jobs available in the USA and Asia please visit our website at https://www.tekfortune.com/careers/ .",
    job_is_remote: false,
    job_posted_at_timestamp: 1701177806,
    job_posted_at_datetime_utc: "2023-11-28T13:23:26.000Z",
    job_city: "Austin",
    job_state: "TX",
    job_country: "US",
    job_latitude: 30.267153,
    job_longitude: -97.74306,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=python+developer+in+texas,+usa&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=python+developer+in+texas,+usa&htidocid=qAguPGTIMiLKIsesAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-12-28T13:30:38.000Z",
    job_offer_expiration_timestamp: 1703770238,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 144,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "10+ years of experience in UNIT test",
        "10+ years of experience in Python FLASK development",
        "8+ years of experience in building API/microservices development",
        "6+ years of experience in GitHub",
        "Hands on experiences in AWS lambda, CloudFront, S3 & EKS",
        "Hands on experience in Docker",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
];
